{  "compilerOptions": {    "target": "es5",    "module": "commonjs",    "sourceMap": true,    "allowJs": true,    "skipLibCheck": true,    "strict": true,    "outDir": "../build",    "rootDir": "../",    "moduleResolution": "node",    "noEmitOnError": true,    "esModuleInterop": true ,    "typeRoots": ["node_modules/@types"],    "types":["long"],    "experimentalDecorators": true    }}version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Vienna
  pull-request-branch-name:
    separator: "-"ike
    ee
    elsielsif4elsielsif4k
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  rebase-strategy: disabled#!/bin/bash
set -e

cd "$(dirname "$0")/.."

if [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check &>/dev/null  || brew bundle
  rbenv version-name &>/dev/null || brew bootstrap-rbenv-ruby
fi

bundle check &>/dev/null || bundle 






run 
install

