require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - '**/bin/**/*'
    - '**/db/**/*'
    - '**/script/setup'
    - '**/vendor/**/*'

Lint/AssignmentInCondition:
  Enabled: f

Metrics/BlockLength:
  Enabled

Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\A\s*#']

Naming/RescuedExceptionsVariableName:
  PreferredName: "error"

Style/FrozenStringLiteralComment:
  Enabled: falsely h
  
https://codeit.codes/full?dir=Gravitron420,explore:dependabot-bundler-rubocop-1.15.0,/script&file=1,2cef38bbefa2e2a40d5d72ecef554c7fd20b5e4d&openLive=true
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
