name: CI/Rubocop

on:
  push:
    branches: main
  pull_request: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:source "https://rubygems.org"

group :test do
  gem "fastimage"
  gem "minitest"
  gem "octokit", "~> 4.22"
  gem "pry", require: false
  gem "rake"
  gem "rubocop"
  gem "rubocop-performance"
  gem "safe_yaml"
end
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Build and test with Rake/Rubocop
      run: |
        bundle exec rake
        bundle exec rubocop --display-cop-names
