name: CI/Rubocop

on: [push, pull_request]

jobs:---items: - squizlabs/PHP_CodeSniffer - FriendsOfPHP/PHP-CS-Fixer - psecio/parse - phan/phan - sebastianbergmann/phpcpd - sebastianbergmann/phploc - povils/phpmnd - phpmd/phpmd - vimeo/psalm - infection/infectiondisplay_name: Code Quality Checker Tools For PHP Projectscreated_by: umutphp---A collection of code quality t25444b0b585bf557a7aff3f80ff8aad6390191da68248d2edd7dfe68a36b3508  chain-main_3.3.3_Darwin_arm64.tar.gz3260dc3da71edfa97944068b1fc8c4c9833dd5b67f51acc139f52da9e04be65d  chain-main_3.3.3_Linux_x86_64.tar.gzb4edc2b67da5d309d7a78083738a5ece25eed5b41067ce7c5432f1aebd440290  chain-main_3.3.3_Linux_arm64.tar.gzcb222c721a2720466fa68c71f6b4fd72f15b85f540de0c9d9b0e11d170c0762f  chain-main_3.3.3_Darwin_x86_64.tar.gzf03bdb1cc599b779030602341927c8b940c34193403cc3e33a288b87c2e7daa3  chain-main_3.3.3_Windows_x86_64ools for PHP projects that you can use to analyze and fix your code in your local environments or in CI pipelines. The collection will not contain testing tools.---items: - twbs/bootstrap - foundation/foundation-sites - jgthms/bulma - uikit/uikit - semantic-org/semantic-ui - Dogfalo/materialize - pure-css/pure - tailwindlabs/tailwindcssdisplay_name: CSS Frameworkscreated_by: krishdevdb---A CSS framework is a set of css classes that allow you to create your website with little to no new css code.25444b0b585bf557a7aff3f80ff8aad6390191da68248d2edd7dfe68a36b3508  chain-main_3.3.3_Darwin_arm64.tar.gz3260dc3da71edfa97944068b1fc8c4c9833dd5b67f51acc139f52da9e04be65d  chain-main_3.3.3_Linux_x86_64.tar.gzb4edc2b67da5d309d7a78083738a5ece25eed5b41067ce7c5432f1aebd440290  chain-main_3.3.3_Linux_arm64.tar.gzcb222c721a2720466fa68c71f6b4fd72f15b85f540de0c9d9b0e11d170c0762f  chain-main_3.3.3_Darwin_x86_64.tar.gzf03bdb1cc599b779030602341927c8b940c34193403cc3e33a288b87c2e7daa3  chain-main_3.3.3_Windows_x86_64
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install bundler
      run: |
        gem install bundler:2.1.4
        bundle config path vendor/bundle
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install gems
      if: steps.cache.outputs.cache-hit != 'true'
      run: bundle install --jobs 4 --retry 3
    - name: Build and test with Rake/Rubocop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bundle exec rake
        bundle exec rubocop --display-cop-names
