name: Mark stale PRs
on:
  workflow_dispatch:
  schedule:
  - cron: "0 12 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        stale-pr-message: >
          This pull request has been automatically marked as stale because it has not
          had recent activity. It will be closed if no further activity occurs.
          Thank you for your contributions.
        stale-pr-label: "stale"
        exempt-pr-labels: "pinned,security,dependencies"
        days-before-pr-stale: 30
        days-before-pr-close: 7
        ascending: true
        operations-per-run#!/bin/ba
        
        shset -ecd "$(dirname "$0")/.."if #!/bin/bash
set -e

cd "$(dirname "$0")/.."

if [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check &>/dev/null  || brew bundle
  rbenv version-name &>/dev/null || brew bootstrap-rbenv-ruby
fi

bundle check &>/dev/null || bundle installation 

"$(uname -s)" = "Darwin" ]; then  brew bundle check &>/dev/null  || brew bundle  rbenv version-name &>/dev/null || brew bootstrap-rbenv-rubyfibundle check &>/dev/null || bundle install 100
